version: "3.8"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  frontend:
    build: ./services/frontend
    ports:
      - 4000:3000

  login:
    build: ./services/login-register
    ports:
      - 4002:3000
    environment:
      APP_NAME: LearnDocker
      PORT: 3000
      DB_URI: mongodb+srv://ananyapromi3:promi3@train.7ag3z.mongodb.net/?retryWrites=true&w=majority&appName=Train/train
    depends_on:
      - mongo_db

  train-search:
    build: ./services/train-search
    ports:
      - 4003:3001
    environment:
      APP_NAME: LearnDocker
      PORT: 3001
      DB_URI: mongodb+srv://ananyapromi3:promi3@train.7ag3z.mongodb.net/?retryWrites=true&w=majority&appName=Train/train
    depends_on:
      - mongo_db
  
  book-ticket:
    build: ./services/book-ticket
    ports:
      - 4004:3002
    environment:
      APP_NAME: LearnDocker
      PORT: 3002
      DB_URI: mongodb+srv://ananyapromi3:promi3@train.7ag3z.mongodb.net/?retryWrites=true&w=majority&appName=Train/train
    depends_on:
      - mongo_db

  otp:
    build: ./services/otp
    ports:
      - 4005:3003
    environment:
      APP_NAME: LearnDocker
      PORT: 3003
      DB_URI: mongodb+srv://ananyapromi3:promi3@train.7ag3z.mongodb.net/?retryWrites=true&w=majority&appName=Train/train
    depends_on:
      - mongo_db

  payment:
    build: ./services/payment
    ports:
      - 4006:3004
    environment:
      APP_NAME: LearnDocker
      PORT: 3004
      DB_URI: mongodb+srv://ananyapromi3:promi3@train.7ag3z.mongodb.net/?retryWrites=true&w=majority&appName=Train/train
    depends_on:
      - mongo_db



volumes:
  mongo_db: {}
