version: "3.8"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: ./services/backend
    ports:
      - 4000:3000
    environment:
      APP_NAME: LearnDocker
      PORT: 3000
      DB_URI: mongodb://mongo_db:27017/dockerlearn
    depends_on:
      - mongo_db
  
  frontend:
    build: ./services/frontend
    ports:
      - 8080:8080

volumes:
  mongo_db: {}
