apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
      - name: login-container
        image: navid67/hackathon_bcf24:login-1.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: LoadBalancer
  selector:
    app: login-service
  ports:
  - protocol: TCP
    port: 4002
    targetPort: 3000
