name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install login-register dependencies
        run: |
          cd services/login-register
          npm install

      - name: Run login-register tests
        run: |
          cd services/login-register
          npm test # Run tests in the login-register

      - name: Install train-search dependencies
        run: |
          cd services/train-search
          npm install

      - name: Run train-search tests
        run: |
          cd services/train-search
          npm test # Run tests in the train-search

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for login-register
        run: |
          cd services/login-register
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dockerlearn:login-register .

      - name: Push Docker image for login-register
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dockerlearn:login-register

      - name: Build Docker image for train-search
        run: |
          cd services/train-search
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dockerlearn:train-search .

      - name: Push Docker image for train-search
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dockerlearn:train-search
